AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda + API Gateway using SAM

Resources:
  TripTrek-API:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: TripTrek-API

  createTrip:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createTrip
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: create/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TripTrek
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /createTrip
            Method: POST
            ApiId: !Ref TripTrek-API

  updateTrip:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateTrip
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: update/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TripTrek
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /updateTrip
            Method: PATCH
            ApiId: !Ref TripTrek-API

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${TripTrek-API}.execute-api.${AWS::Region}.amazonaws.com"