  generateSignedUrl:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: generateSignedUrl
      Handler: generateSignedUrl.handler
      Runtime: nodejs22.x
      CodeUri: generateSignedUrl/
      Environment:
        Variables:
          BUCKET_NAME: my-location-images-bucket
          AWS_REGION: !Ref AWS::Region
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: arn:aws:s3:::my-location-images-bucket/*
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /generateSignedUrl
            Method: POST
            ApiId: !Ref TripTrekAPI
